# Generated by Django 5.1 on 2024-09-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
