# Generated by Django 5.1 on 2024-09-15 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_bids_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(default=0.01),
        ),
    ]
