# Generated by Django 5.1 on 2024-09-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_created_listing_starting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_link',
        ),
    ]
