# Generated by Django 5.1 on 2024-09-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_created_remove_listing_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_link',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
