# Generated by Django 5.1 on 2024-09-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_category_alter_listing_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
