# Generated by Django 5.1 on 2024-09-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchList',
            field=models.ManyToManyField(default=None, null=True, related_name='watchers', to='auctions.listing'),
        ),
    ]
